
version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5431/tcp
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=${PGDATA}
  web:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data:
    driver: local
  web-data:
    driver: local